-- ============================================================
-- VYNTA ANALYTICS SCHEMA v1
-- Event Sourcing + Audience Intelligence
-- ============================================================

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. Raw Events (Event Sourcing)
CREATE TABLE IF NOT EXISTS analytics_events (
    id               UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    project_id       UUID NOT NULL,
    session_id       UUID NOT NULL,
    user_id          UUID,
    event_type       VARCHAR(50) NOT NULL,
    -- 'audio_heartbeat' | 'audio_skip' | 'ai_query' | 'milestone'
    payload          JSONB NOT NULL DEFAULT '{}',
    client_timestamp TIMESTAMPTZ NOT NULL,
    server_timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_events_project_time
    ON analytics_events(project_id, server_timestamp DESC);

CREATE INDEX IF NOT EXISTS idx_events_type
    ON analytics_events(event_type);

CREATE INDEX IF NOT EXISTS idx_events_session
    ON analytics_events(session_id);


-- 2. Sessions (Aggregated state per listening session)
CREATE TABLE IF NOT EXISTS analytics_sessions (
    id                UUID PRIMARY KEY,
    project_id        UUID NOT NULL,
    user_id           UUID,
    start_time        TIMESTAMPTZ NOT NULL,
    end_time          TIMESTAMPTZ,
    total_listen_sec  INTEGER NOT NULL DEFAULT 0,
    queries_count     INTEGER NOT NULL DEFAULT 0,
    skips_count       INTEGER NOT NULL DEFAULT 0,
    -- Derived metrics (updated on session close)
    completion_rate   NUMERIC(5,2),   -- 0-100
    friction_score    NUMERIC(5,4)    -- skips / impressions
);

CREATE INDEX IF NOT EXISTS idx_sessions_project_time
    ON analytics_sessions(project_id, start_time DESC);

CREATE INDEX IF NOT EXISTS idx_sessions_user
    ON analytics_sessions(user_id);


-- 3. AI Insights (Generated by InsightGenerator.ts, consumed by Dashboard)
CREATE TABLE IF NOT EXISTS ai_insights (
    id            UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    project_id    UUID NOT NULL,
    insight_type  VARCHAR(20) NOT NULL DEFAULT 'trend',
    -- 'anomaly' | 'trend' | 'editorial'
    title         TEXT NOT NULL DEFAULT '',
    content       TEXT NOT NULL,
    actionable_advice TEXT,
    is_actioned   BOOLEAN NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_insights_project_time
    ON ai_insights(project_id, created_at DESC);


-- ============================================================
-- HELPER VIEWS
-- ============================================================

-- Daily summary per project (last 24h)
CREATE OR REPLACE VIEW v_daily_summary AS
SELECT
    project_id,
    COUNT(DISTINCT user_id)                                    AS unique_users,
    COUNT(*)                                                   AS total_sessions,
    ROUND(AVG(total_listen_sec) / 60.0, 2)                    AS avg_listen_min,
    ROUND(AVG(completion_rate), 1)                             AS avg_completion_rate,
    SUM(skips_count)                                           AS total_skips,
    SUM(queries_count)                                         AS total_queries,
    ROUND(
        CASE WHEN SUM(total_listen_sec) > 0
             THEN SUM(queries_count)::numeric / (SUM(total_listen_sec) / 60.0)
             ELSE 0 END, 4
    )                                                          AS conversation_lift
FROM analytics_sessions
WHERE start_time >= NOW() - INTERVAL '24 hours'
GROUP BY project_id;


-- Intent clusters: AI queries grouped by keyword (last 24h)
CREATE OR REPLACE VIEW v_intent_clusters AS
SELECT
    project_id,
    payload->>'query'      AS query_text,
    payload->>'category'   AS category,
    COUNT(*)               AS frequency,
    MAX(server_timestamp)  AS last_seen
FROM analytics_events
WHERE event_type = 'ai_query'
  AND server_timestamp >= NOW() - INTERVAL '24 hours'
GROUP BY project_id, payload->>'query', payload->>'category'
ORDER BY frequency DESC;
